### ISSUE TITLE
 *.gif files

### ISSUE THREAD

**Issue by Bishamon1987** [basmilius/weather-icons#15]
Is it possible to convert these animated svg-files as gif-files?
I would love to use them for my personal weatherstation :)

**Comment by doosterkamp** [comment]
https://convertio.co/svg-gif/

**Comment by Bishamon1987** [comment]
> https://convertio.co/svg-gif/

Sadly it doesn't make a animated gif....

**Comment by nelioyann** [comment]
You could convert the lottie files (.json) into gifs using [Lottie converter](https://lottiefiles.com/lottie-to-gif)

**Comment by basmilius** [comment]
I think the lottie converter mentioned by @nelioyann is the best option here. A few weeks ago I tried exporting animated gifs from After Effects, but I'm not really keen on the quality. I'll investigate some more though!

Due to a new job I'm currently not really working that much on this project, but I'm expecting to work again in a few weeks.

**Comment by hoangtran355** [comment]
> You could convert the lottie files (.json) into gifs using [Lottie converter](https://lottiefiles.com/lottie-to-gif)

hello, how do I get the lottie files?

**Comment by basmilius** [comment]
I'm going to finally close this issue. Lotties are the way forward, because they have amazing support across platforms. When v3 will be released in the upcoming weeks, a new set of both svg and lottie files will be available.
